from Python_Project import ex01
from Python_Project import ex02
from Python_Project import ex04
from Python_Project import ex06
from Python_Project import ex08
from Python_Project import ex10
from Python_Project import ex12
from Python_Project import ex14
from Python_Project import ex15
from Python_Project import ex16